name: belajar_dart_packages_application
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

publish_to: none

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  belajar_dart_package:
    git:
      url: git@github.com:bagih/belajar-dart-package.git
      ref: 1.5.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
